name: do things

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: chmod +x ./gradlew
      - name: Build with Gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
        with:
          distributions-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
          arguments: build
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: the jar
          path: build/libs/*.jar
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: AntiP2W-Tools
          DISCORD_AVATAR: https://i.imgur.com/VvG5iFz.png
          DISCORD_EMBEDS: '[{"title":"New Commit ➡️ Click","description":"[Download ➡️ Click](https://github.com/AntiP2WDevelopment/AntiP2W-Addon/actions/runs/${{ github.run_id }})","color":43690,"url":"https://github.com/AntiP2WDevelopment/AntiP2W-Addon/commit/${{ github.sha }}"}]'
        uses: Ilshidur/action-discord@master